/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Published pill feed, newest first
         * @description Requires LEARNER. Served read-through from Redis (60s page TTL).
         */
        get: operations["listPills"];
        put?: never;
        /**
         * Draft a new pill
         * @description Requires AUTHOR. The caller (JWT `sub`) becomes the pill's author.
         */
        post: operations["createPill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Fetch a single pill
         * @description Requires LEARNER. PUBLISHED pills are visible to any authenticated user
         *     (cached read-through, 10m TTL). Unpublished pills are visible only to
         *     their author and CURATOR+; everyone else receives 404 (existence hiding).
         */
        get: operations["getPill"];
        /**
         * Replace a pill's editable fields
         * @description Requires AUTHOR + ownership (CURATOR+ may edit any pill). ARCHIVED pills cannot be edited.
         */
        put: operations["updatePill"];
        post?: never;
        /**
         * Hard-delete a pill
         * @description Requires AUTHOR + ownership (CURATOR+ may delete any pill). Audited (SECURITY.md §4.8).
         */
        delete: operations["deletePill"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pills/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish a pill into the public feed
         * @description Requires CURATOR. Allowed from DRAFT or IN_REVIEW. Audited.
         */
        post: operations["publishPill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PillInput: {
            title: string;
            /** @description Unique across all pills */
            slug: string;
            summary?: string | null;
            /** @description Pill body as an arbitrary JSON document (stored as jsonb) */
            content: Record<string, never>;
            type: components["schemas"]["PillType"];
            estimatedDurationSeconds: number;
        };
        Pill: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            authorId: string;
            title: string;
            slug: string;
            summary: string | null;
            content: Record<string, never>;
            type: components["schemas"]["PillType"];
            status: components["schemas"]["PillStatus"];
            estimatedDurationSeconds: number;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Optimistic-locking version */
            version: number;
        };
        PillPage: {
            content: components["schemas"]["Pill"][];
            page: number;
            size: number;
            totalElements: number;
            totalPages: number;
        };
        /** @enum {string} */
        PillType: "ARTICLE" | "QUIZ" | "FLASHCARD" | "VIDEO";
        /** @enum {string} */
        PillStatus: "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED";
        /** @description RFC 9457 problem details */
        Problem: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            /** @description Field-level validation messages (400 only) */
            errors?: {
                [key: string]: string;
            };
        };
    };
    responses: {
        /** @description Validation failure or malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, expired or invalid JWT */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authenticated but lacking the required role or ownership */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Pill does not exist (or existence is hidden from the caller) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Slug already in use, lifecycle violation, or concurrent modification */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listPills: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of published pills */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PillPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createPill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PillInput"];
            };
        };
        responses: {
            /** @description Pill created as DRAFT */
            201: {
                headers: {
                    /** @description URL of the created pill */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pill"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getPill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pill */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pill"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PillInput"];
            };
        };
        responses: {
            /** @description Updated pill */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pill"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deletePill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    publishPill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published pill */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pill"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
